### ISSUE TITLE
where is tictoc's web fetch script?

### ISSUE THREAD

**Issue by pecliu** [lujqme/douyin#7]
Thank you so much for release this excellent application.
In your readme , you said the params algorithm was found in a web javascript, I wonder which site has that script : )

**Comment by lujqme** [comment]
I said "本应用使用今日头条官网 web 端公开的相应参数算法(见下)".So you can find the function about the params encryption in https://toutiao.com. The detail function is which i pasted in README.

Unfortunately, the algorithm is out of date since I made it public.

In the current time, if you want to crawl the data from douyin app, you should try another way such as using ADB/autojs to control a phone or a simulator, getting the reversed code and some way  I didn't memtion.
